export const DATA_FETCHING = "DATA_FETCHING";
export const DATA_FETCHED_SUCESS = "DATA_FETCHED-SUCESS";
export const DATA_FETCHED_FAIL = "DATA_FETCHED-FAIL";

export const FETCH_RESTAURANT_DATA = "FETCH_RESTAURANT_DATA";
export const FETCH_RESTAURANT_DATA_SUCCESS = "FETCH_RESTAURANT_DATA_SUCCESS";
export const FETCH_RESTAURANT_DATA_FAILED = "FETCH_RESTAURANT_DATA_FAILED";

export const FILTER_ALL = "FILTER_ALL";
export const FILTER_RATING = "FILTER_RATING";
export const FILTER_VEG = "FILTER_VEG";