export const searchSuggestionsData = [
  {
    id: 1,
    restaurantName: "Green Apple",
    restaurantAddress: "Kolkata",
    restaurantRating: 4.5,
    restaurantImage: "",
    restaurantCuisine: "Chinese",
    restaurantType: "Restaurant",
  }
  ,
  {
    id: 2,
    restaurantName: "Green Apple",
    restaurantAddress: "Kolkata",
    restaurantRating: 4.5,
    restaurantImage: "",
    restaurantCuisine: "Chinese",
    restaurantType: "Restaurant",
  },
  {
    id: 3,
    restaurantName: "Green Apple",
    restaurantAddress: "Kolkata",
    restaurantRating: 4.5,
    restaurantImage: "",
    restaurantCuisine: "Chinese",
    restaurantType: "Restaurant",
  },
  {
    id: 4,
    restaurantName: "Green Apple",
    restaurantAddress: "Kolkata",
    restaurantRating: 4.5,
    restaurantImage: "",
    restaurantCuisine: "Chinese",
    restaurantType: "Restaurant",
  },
  {
    id: 5,
    restaurantName: "Green Apple",
    restaurantAddress: "Kolkata",
    restaurantRating: 4.5,
    restaurantImage: "",
    restaurantCuisine: "Chinese",
    restaurantType: "Restaurant",
  },
  {
    id: 6,
    restaurantName: "Green Apple",
    restaurantAddress: "Kolkata",
    restaurantRating: 4.5,
    restaurantImage: "",
    restaurantCuisine: "Chinese",
    restaurantType: "Restaurant",
  },
  {
    id: 7,
    restaurantName: "Green Apple",
    restaurantAddress: "Kolkata",
    restaurantRating: 4.5,
    restaurantImage: "",
    restaurantCuisine: "Chinese",
    restaurantType: "Restaurant",
  },
  {
    id: 8,
    restaurantName: "Green Apple",
    restaurantAddress: "Kolkata",
    restaurantRating: 4.5,
    restaurantImage: "",
    restaurantCuisine: "Chinese",
    restaurantType: "Restaurant",
  },
  {
    id: 9,
    restaurantName: "Green Apple",
    restaurantAddress: "Kolkata",
    restaurantRating: 4.5,
    restaurantImage: "",
    restaurantCuisine: "Chinese",
    restaurantType: "Restaurant",
  },
  {
    id: 10,
    restaurantName: "Green Apple",
    restaurantAddress: "Kolkata",
    restaurantRating: 4.5,
    restaurantImage: "",
    restaurantCuisine: "Chinese",
    restaurantType: "Restaurant",
  },
];